### ISSUE TITLE
Customer Portal Link should change

### ISSUE THREAD

**Issue by rcwong** [ibm-cloud-docs/hardware-firewall-dedicated#12]
Customer Portal Link should change to 'Classic Infrastructure in IBM Cloud' and link to cloud.ibm.com/classic

ex: "From your browser, open Classic Infrastructure in IBM Cloud and log into your account."
rather than "From your browser, open the Customer Portal and log into your account.

**Comment by jared-schwalbe** [comment]
This should probably change for all firewall docs, not just dedicated. Let's see how other teams are handling this first.

**Comment by jbmitch** [comment]
Fixed
