### ISSUE TITLE
Make IP ranges in a consistent format so it can be consumed by automation

### ISSUE THREAD

**Issue by pchiquit** [ibm-cloud-docs/hardware-firewall-dedicated#17]
The page about network IP ranges:
https://console.bluemix.net/docs/infrastructure/hardware-firewall-dedicated/ips.html#ibm-cloud-ip-ranges
is written to be consumed by humans and not by machines. Can we have a page that lists the IP ranges consistently so they easily understood by automation? 
This could be a page in CSV, XML, JSON or whatever machine format that is most convenient.
Thanks

**Comment by jkladis** [comment]
Here's an example from AWS that serves as a base example for what's being consumed:
https://ip-ranges.amazonaws.com/ip-ranges.json

**Comment by jbmitch** [comment]
This is in progress, believe it or not
