### ISSUE TITLE
Modify Cloud IP ranges page

### ISSUE THREAD

**Issue by guillenunez28** [ibm-cloud-docs/hardware-firewall-dedicated#29]
Change this statement: 
"A frequently asked question is What IP ranges do I allow through the firewall?. The following list contains the full range of IPs to use with the following IBM© firewalls and appliances:"

to avoid customer confusion. It seems like the IP range on this page has to be used for firewalls. 

https://cloud.ibm.com/docs/infrastructure/hardware-firewall-dedicated?topic=hardware-firewall-dedicated-ibm-cloud-ip-ranges

Review the page to ensure the information is still relevant.

**Comment by jbmitch** [comment]
Fixed
