### ISSUE TITLE
Subnet for  169.63.30.n is missing from public documention

### ISSUE THREAD

**Issue by naterry** [ibm-cloud-docs/hardware-firewall-dedicated#30]
Hi,

We have provisioned a new IAE cluster whose IP address is  169.63.30.n . The subnet to which this IP address belongs in not in the list of subnets for IBM Cloud.  Can you please update the documentation accordingly.

Thanks

**Comment by jbmitch** [comment]
Will be fixed as part of the Service IP reorg effort
