### ISSUE TITLE
need IBM Cloud IP ranges in more consumable format (json)

### ISSUE THREAD

**Issue by lilorozco** [ibm-cloud-docs/hardware-firewall-dedicated#33]
Martin Bosch 3:56 PM
CS1626039 - i was pointed your way by viktoria muirhead. this customer is asking if it would be possible to publish something like https://docs.aws.amazon.com/general/latest/gr/aws-ip-ranges.html which would include all Cloud Object Storage service IPs/subnets in a consumable JSON format. do you have any advice on how to go about requesting that be done or otherwise? the closest thing we seem to have is https://cloud.ibm.com/docs/infrastructure/gateway-appliance?topic=hardware-firewall-dedicated-ibm-cloud-ip-ranges (edited) 
which doesn't include all service IPs such as those used for Cloud Object Storage cross regional endpoints (edited) 
we also have this but it doesnt list the associated IPs/subnets
https://cloud.ibm.com/docs/services/cloud-object-storage?topic=cloud-object-storage-endpoints
also these documents arent in such a  programmatically consumable  format (JSON) as Amazon's (edited)

**Comment by jbmitch** [comment]
In progress
