### ISSUE TITLE
10.3.118.02/24 is an invalid network

### ISSUE THREAD

**Issue by sdouglas-skytap** [ibm-cloud-docs/hardware-firewall-dedicated#36]
👋  I believe the network `10.3.118.02/24` specified in https://github.com/ibm-cloud-docs/hardware-firewall-dedicated/blob/master/ips.md is invalid. I think it was a typo and should be `10.3.118.0/24`. Looks like this was added in 20d873aad7ffa4f964814f7f8808bb1701514175.

Can submit a PR, but wanted to talk about it first.

**Comment by jbmitch** [comment]
Fixed
