### ISSUE TITLE
Add SAO04/05 (new DC) Services Subnets

### ISSUE THREAD

**Issue by moe-shah** [ibm-cloud-docs/hardware-firewall-dedicated#39]
SAO04/05 are new DC's that were launched 3/15. Please add the Service network subnets

sao04 | São Paulo | - | BRA | 10.202.208.0/20
sao05 | São Paulo | - | BRA | 10.202.240.0/20

thanks

**Comment by austinmama** [comment]
This information also came in via: https://github.com/ibm-cloud-docs/hardware-firewall-dedicated/issues/39

**Comment by jbmitch** [comment]
Added
