### ISSUE TITLE
Remove references of 2020 DCs decommissioned from https://cloud.ibm.com/docs/virtual-router-appliance?topic=hardware-firewall-dedicated-ibm-cloud-ip-ranges page

### ISSUE THREAD

**Issue by smithajayaram** [ibm-cloud-docs/hardware-firewall-dedicated#40]
Please remove references of datacenters decommissioned in 2020 from this page - https://cloud.ibm.com/docs/virtual-router-appliance?topic=hardware-firewall-dedicated-ibm-cloud-ip-ranges

These DCs include - SEA01, MEL01 and DAL07

**Comment by jbmitch** [comment]
Fixed, give it time to replicate. In the future, please post issues and pull requests on the staging server, not on production. Comments on production get lost easily, and cannot be merged directly. All new content should source in staging, initially.
