### ISSUE TITLE
Same IP Range for two different DOS Mitigation System entries

### ISSUE THREAD

**Issue by Justicelemon** [ibm-cloud-docs/hardware-firewall-dedicated#7]
Both the KOR and NOR Datacenters have 169.56.116.0/24 listed as their IP Range.

EDIT: Actually, there's quite a few different datacenters with the same IP range, what does this mean?

**Comment by austinmama** [comment]
@jbmitch

**Comment by jbmitch** [comment]
Forwarded to development
